version: "3"
services:  
  elasticsearch: 
    container_name: elasticsearch
    image: elasticsearch:7.11.1 
    restart: always
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data #maintain the data in elastic search even if crashed
    
  kibana:
    container_name: kibana
    image: kibana:7.11.1
    restart: always
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    
  logstash:
    container_name: logstash
    image: logstash:7.11.1
    restart: always
    volumes:
      - ./logstash-conf/:/usr/share/logstash/pipeline/
    ports:
      - 5044:5044
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data-volume:
    driver: local
    